/*
http://projecteuler.net/problem=2

Even Fibonacci numbers

Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

const int limit = 4000000;

int main()
{

	int v = 0; // store the current value
	int p_1 = 0; // store the last value
	int p_2 = 1;
	int sum = 0;

	while (v<limit) {
		// loop generates the fibonacci sequence
	  
		v = p_1 + p_2;
		p_1 = p_2;
		p_2 = v;

		if (v%2==0)
			sum=sum+v;

	}

	printf("%d \n",sum);

	return 0;
}

